# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: list # all, none, or list of linter keys
DISABLE:
  # temporary (March 2023)
  - COPYPASTE
DISABLE_LINTERS:
  # temporary fix for https://github.com/oxsecurity/megalinter/issues/1664
  - REPOSITORY_DEVSKIM
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
REPOSITORY_DEVSKIM_ARGUMENTS: ["--ignore-globs", "**/node_modules/**"]
JSON_JSONLINT_ARGUMENTS: "--comments"
REPOSITORY_CHECKOV_ARGUMENTS: "--skip-path=.github"
ACTION_ACTIONLINT_ARGUMENTS: "-ignore SC2086"
