export * from './base.page';
export * from './configuration.page';
export * from './content-management.page';
export * from './dashboard.page';
export * from './home.page';
export * from './login.page';
export * from './scheduled-event.page';
export * from './user.page';
export * from './scenarios.page'
export * from './courses.page'