name: Run e2e tests
description: Execute end-2-end tests on a given HobbyFarm instance

inputs:
  adminui_password:
    description: Admin UI Password
    required: true
  adminui_password_hashpwd:
    description: Admin UI Hash Password
    required: false
    default: ""
  adminui_url:
    description: Admin UI URL
    required: true
  adminui_username:
    description: Admin UI Username
    required: true
  adminui_version:
    description: Admin UI Version
    required: true
  artifact_retention_days:
    description: Number of days to keep the artifacts
    required: false
    default: "2"
  environment:
    description: Environment
    required: false
    default: ""
  gargantua_url:
    description: Gargantua URL
    required: true
  playwright_options:
    description: Playwright test run options
    required: false
    default: "readonly --project chromium"
    # examples: "readonly provision --project chromium"
  run_acceptance_tests:
    description: Should we run the acceptance tests?
    required: false
    default: "false"
  scenario:
    description: Scenario
    required: false
    default: ""
  ui_hometitle:
    description: UI Home Title
    required: true
  ui_url:
    description: UI URL
    required: true
  ui_version:
    description: UI Version
    required: true
  working_directory:
    description: Working directory
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
    #   name: List the state of node modules
    #   continue-on-error: true
    #   run: npm list
    #   shell: bash
    - name: Use Playwright cache
      id: playwright-cache
      uses: actions/cache@v3
      with:
        path: /home/runner/.cache/ms-playwright
        key: ${{ runner.os }}-playwright
    - name: Install dependencies
      run: |
        npm install
        npx playwright install --with-deps
      working-directory: ${{ inputs.working_directory }}
      shell: bash
    - name: Run tests
      run: npx playwright test --trace on --reporter junit,html ${{ inputs.playwright_options }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        HOBBYFARM_ADMIN_UI_HASHPWD: "${{ inputs.adminui_password_hashpwd }}"
        HOBBYFARM_ADMIN_UI_PWD: ${{ inputs.adminui_password }}
        HOBBYFARM_ADMIN_UI_URL: ${{ inputs.adminui_url }}
        HOBBYFARM_ADMIN_UI_USR: ${{ inputs.adminui_username }}
        HOBBYFARM_ADMIN_UI_VERSION: ${{ inputs.adminui_version }}
        HOBBYFARM_EVENT_SCENARIO: ${{ inputs.scenario }}
        HOBBYFARM_EVENT_ENVIRONMENT: ${{ inputs.environment }}
        HOBBYFARM_GARGANTUA_URL: ${{ inputs.gargantua_url }}
        HOBBYFARM_UI_HEADER_TITLE: ${{ inputs.ui_hometitle }}
        HOBBYFARM_UI_URL: ${{ inputs.ui_url }}
        HOBBYFARM_UI_VERSION: ${{ inputs.ui_version }}
        PLAYWRIGHT_JUNIT_OUTPUT_NAME: results.xml
    - name: Run acceptance tests against local environment
      if: inputs.run_acceptance_tests == 'true'
      run: npx cucumber-js
      shell: bash
      env:
        HOBBYFARM_ADMIN_UI_HASHPWD: "${{ inputs.adminui_password_hashpwd }}"
        HOBBYFARM_ADMIN_UI_PWD: ${{ inputs.adminui_password }}
        HOBBYFARM_ADMIN_UI_URL: ${{ inputs.adminui_url }}
        HOBBYFARM_ADMIN_UI_USR: ${{ inputs.adminui_username }}
        HOBBYFARM_ADMIN_UI_VERSION: ${{ inputs.adminui_version }}
        HOBBYFARM_EVENT_SCENARIO: ${{ inputs.scenario }}
        HOBBYFARM_EVENT_ENVIRONMENT: ${{ inputs.environment }}
        HOBBYFARM_GARGANTUA_URL: ${{ inputs.gargantua_url }}
        HOBBYFARM_UI_HEADER_TITLE: ${{ inputs.ui_hometitle }}
        HOBBYFARM_UI_URL: ${{ inputs.ui_url }}
        HOBBYFARM_UI_VERSION: ${{ inputs.ui_version }}
    - name: Save pipeline artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: |
          ${{ inputs.working_directory }}/playwright-report/
          ${{ inputs.working_directory }}/test-results/
          ${{ inputs.working_directory }}/results.xml
        retention-days: ${{ inputs.artifact_retention_days }}
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: ${{ inputs.working_directory }}/results.xml
