# purpose: run Continuous Integration (build, unit test, lint, scan)

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# warn: limitation on write for PR from forked repo
permissions:
  contents: read
  checks: write
  id-token: write
  pull-requests: write

jobs:
  build-test:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # full git history is needed to get a proper list of changed files
          fetch-depth: 0
      - name: Check NPM package version
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        run: |
          package_name=$(npm list --json --depth=0 | sed -n 3p | cut -d '"' -f4)
          new_package_version=$(npm list --json --depth=0 | sed -n 2p | cut -d '"' -f4)
          if npm show $package_name@$new_package_version version > /dev/null 2>&1 ; then
            echo Version $package_name@$new_package_version exists. Please increase the version in package.json file.
            exit 1
          fi
      # TODO: scan code with SonarCloud
      - name: Install k3d
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Create a local Kubernetes cluster with k3d
        run: scripts/create_kubernetes_cluster.sh
      - name: Install HobbyFarm in the local cluster
        run: scripts/install_hobbyfarm.sh
      - name: Run e2e tests
        uses: ./.github/actions/e2e-testing
        with:
          adminui_password: admin
          adminui_password_hashpwd: ${{ env.HOBBYFARM_ADMIN_UI_HASHPWD }}
          adminui_url: https://admin.hf.local
          adminui_username: admin
          adminui_version: 2.0.3
          ui_hometitle: Rancher HobbyFarm
          ui_url: https://learn.hf.local
          ui_version: 2.0.2
          gargantua_url: https://api.hf.local
          playwright_options: "--global-timeout 360000 --project=chromium --workers=1 --grep-invert @notci"
          run_acceptance_tests: "true"
          artifact_retention_days: 7
    env:
      # looks like a secret but it is a generic value (and we can't access secrets on a pull-request event, see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#accessing-secrets)
      HOBBYFARM_ADMIN_UI_HASHPWD: "$2a$10$33fQs0G.lHQdDAsdoECgA.8iYvNtyJ2XC2AmvR5x6ZkzxSuKXyfFm"
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # full git history is needed to get a proper list of changed files
          fetch-depth: 0
      - name: Lint codebase
        # hint: https://github.com/marketplace/actions/super-linter was too outdated and complicated to configure
        uses: oxsecurity/megalinter@v6
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Save pipeline artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lint-reports
          path: |
            megalinter-reports/
            mega-linter.log
          retention-days: 7
