# purpose: run Continuous Integration (build, unit test, lint, scan)
# uses:
#   - https://github.com/github/super-linter

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

concurrency:
  group: "ci"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup NPM cache
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install NPM packages
        run: npm install
      - name: Lint codebase
        uses: github/super-linter@v4.10.1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # hack: enable when https://github.com/github/super-linter/issues/3965 is fixed
          VALIDATE_GITHUB_ACTIONS: false
      # TODO: sonar, tests
      - name: Install k3d
        run: wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Create local Kubernetes cluster with k3d
        run: k3d cluster create k3d-local
