# purpose: run Continuous Integration (build, unit test, lint, scan)
# actions:
#   - https://github.com/marketplace/actions/megalinter
# images:
#   - https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch: {}

concurrency:
  group: "ci"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo $HOBBYFARM_ADMIN_UI_URL
          echo $HOBBYFARM_ADMIN_UI_HASHPWD
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # full git history is needed to get a proper list of changed files
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup NPM cache
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install NPM packages
        run: npm install
      - name: Lint codebase
        # hint: https://github.com/marketplace/actions/super-linter was too outdated and complicated to configure
        uses: oxsecurity/megalinter@v6
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # TODO: scan code with SonarCloud
      - name: Install k3d
        run: curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
      - name: Create a local Kubernetes cluster with k3d
        run: scripts/create_kubernetes_cluster.sh
      - name: Install HobbyFarm in the local cluster
        run: scripts/install_hobbyfarm.sh
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests against local environment
        run: npx playwright test --trace on --global-timeout 180000
      - name: Run acceptance tests against local environment
        run: npx cucumber-js
      - name: Save pipeline artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: code-quality-reports
          path: |
            playwright-report/
            megalinter-reports/
            mega-linter.log
            cucumber-report.html
          retention-days: 30
      - name: Clean-up containers
        run: scripts/delete_kubernetes_cluster.sh
      # TODO: publich tests as NPM package (GitHub registry)
    env:
      HOBBYFARM_ADMIN_UI_URL: https://admin.hf.local
      HOBBYFARM_ADMIN_UI_USR: admin
      HOBBYFARM_ADMIN_UI_PWD: admin
      HOBBYFARM_ADMIN_UI_HASHPWD: "${{ vars.LOCAL_ADMIN_UI_HASHPWD }}"
      HOBBYFARM_UI_HEADER_TITLE: Rancher HobbyFarm
      HOBBYFARM_UI_URL: https://learn.hf.local
      HOBBYFARM_GARGANTUA_URL: https://api.hf.local
