# purpose: execute every night the test suite on a given environment

name: Nightly

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  staging-testing:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Debug variables
        run: |
          echo $HOBBYFARM_UI_HEADER_TITLE
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Setup NPM cache
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install NPM packages
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests against Staging environment
        run: npx playwright test --trace on
      - name: Run acceptance tests against Staging environment
        run: npx cucumber-js
      - name: Save pipeline artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            cucumber-report.html
          retention-days: 30
    env:
      HOBBYFARM_ADMIN_UI_URL: ${{ secrets.STAGING_ADMIN_UI_URL }}
      HOBBYFARM_ADMIN_UI_USR: ${{ secrets.STAGING_ADMIN_UI_USR }}
      HOBBYFARM_ADMIN_UI_PWD: ${{ secrets.STAGING_ADMIN_UI_PWD }}
      HOBBYFARM_ADMIN_UI_VERSION: ${{ vars.STAGING_ADMIN_UI_VERSION }}
      HOBBYFARM_UI_HEADER_TITLE: ${{ vars.STAGING_UI_HEADER_TITLE }}
      HOBBYFARM_UI_URL: ${{ secrets.STAGING_UI_URL }}
      HOBBYFARM_UI_VERSION: ${{ vars.STAGING_UI_VERSION }}
      HOBBYFARM_GARGANTUA_URL: ${{ secrets.STAGING_GARGANTUA_URL }}
