# purpose: execute every night the test suite on a given environment

name: Nightly

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: {}

jobs:
  staging-testing:
    name: Staging smoke tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run e2e tests
        uses: ./.github/actions/e2e-testing
        with:
          adminui_password: ${{ secrets.STAGING_ADMIN_UI_PWD }}
          adminui_password_hashpwd: ${{ env.HOBBYFARM_ADMIN_UI_HASHPWD }}
          adminui_url: ${{ secrets.STAGING_ADMIN_UI_URL }}
          adminui_username: ${{ secrets.STAGING_ADMIN_UI_USR }}
          adminui_version: ${{ vars.STAGING_ADMIN_UI_VERSION }}
          ui_hometitle: ${{ vars.STAGING_UI_HEADER_TITLE }}
          ui_url: ${{ secrets.STAGING_UI_URL }}
          ui_version: ${{ vars.STAGING_UI_VERSION }}
          gargantua_url: ${{ secrets.STAGING_GARGANTUA_URL }}
          playwright_options: "--grep-invert @notci"
          run_acceptance_tests: "true"
          artifact_retention_days: 7
        env:
          # looks like a secret but it is a generic value (and we can't access secrets on a pull-request event, see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#accessing-secrets)
          HOBBYFARM_ADMIN_UI_HASHPWD: "$2a$10$33fQs0G.lHQdDAsdoECgA.8iYvNtyJ2XC2AmvR5x6ZkzxSuKXyfFm"
